// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var Respect = require("re-respect/lib/js/src/Respect.js");

Curry._1(Respect.Dsl[/* Async */12][/* register */3], Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "Mongo", /* :: */[
          Curry._2(Respect.Dsl[/* Async */12][/* it */1], "has a failing test", (function (_, don) {
                  return Curry._2(don, /* Some */["err"], /* () */0);
                })),
          /* [] */0
        ]));

/*  Not a pure module */
