// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var MongoDB = require("../src/MongoDB.bs.js");
var Respect = require("re-respect/lib/js/src/Respect.js");

function callbackConverter(x) {
  return Curry._1(x, ( undefined ));
}

var AsyncHandler = /* module */[/* callbackConverter */callbackConverter];

var include = MongoDB.Make(AsyncHandler);

var connect = include[5];

var Mongo_004 = /* Cursor */include[0];

var Mongo_005 = /* InsertResult */include[1];

var Mongo_006 = /* DeleteResult */include[2];

var Mongo_007 = /* Collection */include[3];

var Mongo_008 = /* Db */include[4];

var Mongo = /* module */[
  /* MongoError */MongoDB.MongoError,
  /* ObjectID */MongoDB.ObjectID,
  /* Make */MongoDB.Make,
  /* AsyncHandler */AsyncHandler,
  Mongo_004,
  Mongo_005,
  Mongo_006,
  Mongo_007,
  Mongo_008,
  /* connect */connect
];

Curry._1(Respect.Dsl[/* Async */12][/* register */3], Curry._2(Respect.Dsl[/* Async */12][/* describe */2], "Connection with promise", /* :: */[
          Curry._2(Respect.Dsl[/* Async */12][/* it */1], "Succeeds on a good port", (function (_, don) {
                  Curry._1(connect, "mongodb://127.0.0.1:27019").then((function () {
                          Curry._2(don, /* None */0, /* () */0);
                          return Promise.resolve(/* () */0);
                        }));
                  return /* () */0;
                })),
          /* :: */[
            Curry._2(Respect.Dsl[/* Async */12][/* it */1], "Fails on a bad port", (function (_, don) {
                    Curry._1(connect, "mongodb://127.0.0.1:9999").then((function () {
                              return Promise.resolve(Curry._2(don, /* Some */["We should have failed"], /* () */0));
                            })).catch((function () {
                            return Promise.resolve(Curry._2(don, /* None */0, /* () */0));
                          }));
                    return /* () */0;
                  })),
            /* [] */0
          ]
        ]));

exports.Mongo = Mongo;
/* include Not a pure module */
