// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var Mongodb = require("mongodb");

var MongoError = /* module */[];

var ObjectID = /* module */[];

function Make(Handler) {
  var toArray = function (cursor) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return cursor.toArray(param);
                }));
  };
  var Cursor = /* module */[/* toArray */toArray];
  var InsertResult = /* module */[];
  var DeleteResult = /* module */[];
  var insertOne = function (doc, col) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return col.insertOne(doc, param);
                }));
  };
  var findOne = function (doc, col) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return col.findOne(doc, param);
                }));
  };
  var deleteOne = function (doc, col) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return col.deleteOne(doc, param);
                }));
  };
  var createIndex = function (index, options, col) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return col.createIndex(index, options, param);
                }));
  };
  var createIndexNoOpts = function (index, col) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return col.createIndex(index, param);
                }));
  };
  var Collection = /* module */[
    /* insertOne */insertOne,
    /* findOne */findOne,
    /* deleteOne */deleteOne,
    /* createIndex */createIndex,
    /* createIndexNoOpts */createIndexNoOpts
  ];
  var collection = function (name, conn) {
    return conn.collection(name);
  };
  var Db = /* module */[/* collection */collection];
  var connect = function (url) {
    return Curry._1(Handler[/* callbackConverter */0], (function (param) {
                  return Mongodb.connect(url, param);
                }));
  };
  return /* module */[
          /* Cursor */Cursor,
          /* InsertResult */InsertResult,
          /* DeleteResult */DeleteResult,
          /* Collection */Collection,
          /* Db */Db,
          /* connect */connect
        ];
}

exports.MongoError = MongoError;
exports.ObjectID   = ObjectID;
exports.Make       = Make;
/* mongodb Not a pure module */
